//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCWindow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRCWindow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимые лица: {0}.
        /// </summary>
        internal static string AcceptList {
            get {
                return ResourceManager.GetString("AcceptList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнение.
        /// </summary>
        internal static string Addon {
            get {
                return ResourceManager.GetString("Addon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (автор - {1}).
        /// </summary>
        internal static string AddonDesription {
            get {
                return ResourceManager.GetString("AddonDesription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в дополнении {0}:.
        /// </summary>
        internal static string AddonError {
            get {
                return ResourceManager.GetString("AddonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнение успешно установлено!.
        /// </summary>
        internal static string AddonInstalledSuccessfully {
            get {
                return ResourceManager.GetString("AddonInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данное дополнение уже было установлено ранее. Переустановить его?.
        /// </summary>
        internal static string AddonIsInstalled {
            get {
                return ResourceManager.GetString("AddonIsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        internal static string AdminMailMessage {
            get {
                return ResourceManager.GetString("AdminMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже зарегистрировались.
        /// </summary>
        internal static string AlreadyRegisteredMessage {
            get {
                return ResourceManager.GetString("AlreadyRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение папки данных.
        /// </summary>
        internal static string AppDataFolder {
            get {
                return ResourceManager.GetString("AppDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес, по которому хранятся логи, аддоны и мультимедиа данного пользователя Цирцеи.
        /// </summary>
        internal static string AppDataFolderDescription {
            get {
                return ResourceManager.GetString("AppDataFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык программы.
        /// </summary>
        internal static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для смены языка следует перезапустить программу.
        /// </summary>
        internal static string AppLanguageDescription {
            get {
                return ResourceManager.GetString("AppLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_cascade {
            get {
                object obj = ResourceManager.GetObject("application_cascade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_tile_horizontal {
            get {
                object obj = ResourceManager.GetObject("application_tile_horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_tile_vertical {
            get {
                object obj = ResourceManager.GetObject("application_tile_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ur-quan1986.livejournal.com/74013.html?mode=reply&amp;subject=Замечания по Цирцее.
        /// </summary>
        internal static string AuthorSiteUrl {
            get {
                return ResourceManager.GetString("AuthorSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные дополнения.
        /// </summary>
        internal static string AvailableAddons {
            get {
                return ResourceManager.GetString("AvailableAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные видео, изображения и звуки.
        /// </summary>
        internal static string AvailableMultimedia {
            get {
                return ResourceManager.GetString("AvailableMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ушёл.
        /// </summary>
        internal static string Away {
            get {
                return ResourceManager.GetString("Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} отошёл со словами: {1}.
        /// </summary>
        internal static string AwayWithWords {
            get {
                return ResourceManager.GetString("AwayWithWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фон.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный канал/маска &quot;{0}&quot;!.
        /// </summary>
        internal static string BadChanMaskMessage {
            get {
                return ResourceManager.GetString("BadChanMaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимый ник:.
        /// </summary>
        internal static string BadNick {
            get {
                return ResourceManager.GetString("BadNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете войти на канал {0}, поскольку забанены на нём (+b)!.
        /// </summary>
        internal static string BannedFormChannelMessage {
            get {
                return ResourceManager.GetString("BannedFormChannelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно изменить ник, пока он забанен или используется на модерируемом канале.
        /// </summary>
        internal static string BanNickChangeMessage {
            get {
                return ResourceManager.GetString("BanNickChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование списка банов.
        /// </summary>
        internal static string BansEdit {
            get {
                return ResourceManager.GetString("BansEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бот.
        /// </summary>
        internal static string Bot {
            get {
                return ResourceManager.GetString("Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По умолчанию.
        /// </summary>
        internal static string ByDefault {
            get {
                return ResourceManager.GetString("ByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно подключиться.
        /// </summary>
        internal static string CannotJoin {
            get {
                return ResourceManager.GetString("CannotJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете убить сервер!.
        /// </summary>
        internal static string CannotKillServer {
            get {
                return ResourceManager.GetString("CannotKillServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отправить на канал.
        /// </summary>
        internal static string CannotSendToChannel {
            get {
                return ResourceManager.GetString("CannotSendToChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} поменял(а) ник на {1}.
        /// </summary>
        internal static string ChangeNickTo {
            get {
                return ResourceManager.GetString("ChangeNickTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap channel {
            get {
                object obj = ResourceManager.GetObject("channel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка списка IRC каналов.
        /// </summary>
        internal static string ChannelListConfig {
            get {
                return ResourceManager.GetString("ChannelListConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режимы.
        /// </summary>
        internal static string ChannelModes {
            get {
                return ResourceManager.GetString("ChannelModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не существует ник/канал.
        /// </summary>
        internal static string ChannelNickDoesNotExistst {
            get {
                return ResourceManager.GetString("ChannelNickDoesNotExistst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не оператор на канале!.
        /// </summary>
        internal static string ChannelOpPrivsNeeded {
            get {
                return ResourceManager.GetString("ChannelOpPrivsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каналы.
        /// </summary>
        internal static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема канала.
        /// </summary>
        internal static string ChannelTopic {
            get {
                return ResourceManager.GetString("ChannelTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влияет только на вновь возникающий текст.
        /// </summary>
        internal static string ChatFontDescription {
            get {
                return ResourceManager.GetString("ChatFontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите для подключения.
        /// </summary>
        internal static string ClickToConnect {
            get {
                return ResourceManager.GetString("ClickToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть окно и все подчинённые окна.
        /// </summary>
        internal static string CloseToolTip {
            get {
                return ResourceManager.GetString("CloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы палитры цветов.
        /// </summary>
        internal static string ColorPaletteFiles {
            get {
                return ResourceManager.GetString("ColorPaletteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настроить.
        /// </summary>
        internal static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение к.
        /// </summary>
        internal static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключиться к серверу.
        /// </summary>
        internal static string ConnectToServer {
            get {
                return ResourceManager.GetString("ConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архив был скачан в папку мультимедиа, но не обнаружена программа для его распаковки! Поддерживаемые распаковщики: WinRAR, 7Zip..
        /// </summary>
        internal static string CouldNotUnpack {
            get {
                return ResourceManager.GetString("CouldNotUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат времени.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определите, как выводится время на канале. Обозначения: yyyy - годы, MM - месяцы, dd - дни, HH - часы, mm - минуты, ss - секунды, FF - миллисекунды. (http://msdn.microsoft.com/en-us/library/8kb3ddd4(VS.96).aspx).
        /// </summary>
        internal static string DateTimeFormatDescription {
            get {
                return ResourceManager.GetString("DateTimeFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email адрес.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец списка допустимых лиц.
        /// </summary>
        internal static string EndOfAcceptList {
            get {
                return ResourceManager.GetString("EndOfAcceptList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец данных.
        /// </summary>
        internal static string EndOfData {
            get {
                return ResourceManager.GetString("EndOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершение помощи.
        /// </summary>
        internal static string EndOfHelp {
            get {
                return ResourceManager.GetString("EndOfHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец информации о сервере.
        /// </summary>
        internal static string EndOfInfo {
            get {
                return ResourceManager.GetString("EndOfInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец списка..
        /// </summary>
        internal static string EndOfList {
            get {
                return ResourceManager.GetString("EndOfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершение передачи сообщения дня..
        /// </summary>
        internal static string EndOfMOTD {
            get {
                return ResourceManager.GetString("EndOfMOTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец статистики.
        /// </summary>
        internal static string EndOfStats {
            get {
                return ResourceManager.GetString("EndOfStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец трассировки.
        /// </summary>
        internal static string EndOfTrace {
            get {
                return ResourceManager.GetString("EndOfTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец информации о {0}.
        /// </summary>
        internal static string EndOfWhoList {
            get {
                return ResourceManager.GetString("EndOfWhoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конец исторической информации.
        /// </summary>
        internal static string EndOfWhoWas {
            get {
                return ResourceManager.GetString("EndOfWhoWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите максимальное число пользователей.
        /// </summary>
        internal static string EnterLimit {
            get {
                return ResourceManager.GetString("EnterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ник собеседника.
        /// </summary>
        internal static string EnterNick {
            get {
                return ResourceManager.GetString("EnterNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите слова.
        /// </summary>
        internal static string EnterWords {
            get {
                return ResourceManager.GetString("EnterWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обработать входящее сообщение сервера: {0}. Обратитесь к разработчику.
        /// </summary>
        internal static string ErrorInMessage {
            get {
                return ResourceManager.GetString("ErrorInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка: {0}.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка! Описание ошибки можно сохранить в файл и отправить разработчику. Спасибо!.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование списка антибанов.
        /// </summary>
        internal static string ExemptsEdit {
            get {
                return ResourceManager.GetString("ExemptsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт загрузка файла....
        /// </summary>
        internal static string FileDownloading {
            get {
                return ResourceManager.GetString("FileDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим мигания главного окна.
        /// </summary>
        internal static string FlashingParams {
            get {
                return ResourceManager.GetString("FlashingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to для.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мигать при получении любого сообщения.
        /// </summary>
        internal static string FullFlashMode {
            get {
                return ResourceManager.GetString("FullFlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружены накопительные обновления программы от {0}. Будет произведена дополнительная установка. Загрузить обновления сейчас?.
        /// </summary>
        internal static string FullUpdates {
            get {
                return ResourceManager.GetString("FullUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружено обновление программы до версии {0}. Будет произведена дополнительная установка. Загрузить обновление сейчас?.
        /// </summary>
        internal static string FullUpdatesNew {
            get {
                return ResourceManager.GetString("FullUpdatesNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κίρκη.
        /// </summary>
        internal static string GreekProgramName {
            get {
                return ResourceManager.GetString("GreekProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружены обновления программы до версии {0}. Загрузить их сейчас?.
        /// </summary>
        internal static string HasUpdates {
            get {
                return ResourceManager.GetString("HasUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь не найдена!.
        /// </summary>
        internal static string HelpNotFoundMessage {
            get {
                return ResourceManager.GetString("HelpNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть панель редактирования.
        /// </summary>
        internal static string HideEditorPanel {
            get {
                return ResourceManager.GetString("HideEditorPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя хоста.
        /// </summary>
        internal static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время простоя.
        /// </summary>
        internal static string IdleTime {
            get {
                return ResourceManager.GetString("IdleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя канала содержит недопустимые символы!.
        /// </summary>
        internal static string IncorrectCharactersInChannelName {
            get {
                return ResourceManager.GetString("IncorrectCharactersInChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о.
        /// </summary>
        internal static string InformationAbout {
            get {
                return ResourceManager.GetString("InformationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Находится в режиме +g (игнорируется сервером).
        /// </summary>
        internal static string InGMode {
            get {
                return ResourceManager.GetString("InGMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Была произведена попытка сохранить установленные файлы в папку {0}, но она уже существует! Поэтому файлы находятся по адресу {1}.
        /// </summary>
        internal static string InstallCopyBadTry {
            get {
                return ResourceManager.GetString("InstallCopyBadTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установщик.
        /// </summary>
        internal static string Installer {
            get {
                return ResourceManager.GetString("Installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        internal static string InstallError {
            get {
                return ResourceManager.GetString("InstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инсталлировать в программу новые дополнения с сайта автора или с диска.
        /// </summary>
        internal static string InstallToolTip {
            get {
                return ResourceManager.GetString("InstallToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование списка свободных от лимита.
        /// </summary>
        internal static string InviteEdit {
            get {
                return ResourceManager.GetString("InviteEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы приглашены пользователем {0} на {1}.
        /// </summary>
        internal static string InviteMessage {
            get {
                return ResourceManager.GetString("InviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход на канал {0} только по приглашению (+i)!.
        /// </summary>
        internal static string InviteOnly {
            get {
                return ResourceManager.GetString("InviteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвета IRC.
        /// </summary>
        internal static string IRCColors {
            get {
                return ResourceManager.GetString("IRCColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRC-оператор.
        /// </summary>
        internal static string IRCOp {
            get {
                return ResourceManager.GetString("IRCOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка списка IRC серверов.
        /// </summary>
        internal static string IRCServerListConfig {
            get {
                return ResourceManager.GetString("IRCServerListConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальный размер окон IRC.
        /// </summary>
        internal static string IRCWindowSize {
            get {
                return ResourceManager.GetString("IRCWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доступен для помощи.
        /// </summary>
        internal static string IsAvailableForHelp {
            get {
                return ResourceManager.GetString("IsAvailableForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не активен {0} секунд.
        /// </summary>
        internal static string IsIdleForSeconds {
            get {
                return ResourceManager.GetString("IsIdleForSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to является оператором IRC.
        /// </summary>
        internal static string IsIRCOp {
            get {
                return ResourceManager.GetString("IsIRCOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оффлайн.
        /// </summary>
        internal static string IsOffline {
            get {
                return ResourceManager.GetString("IsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Находится на каналах:.
        /// </summary>
        internal static string IsOnChannels {
            get {
                return ResourceManager.GetString("IsOnChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to онлайн.
        /// </summary>
        internal static string IsOnline {
            get {
                return ResourceManager.GetString("IsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Находятся онлайн: {0}.
        /// </summary>
        internal static string IsOnReply {
            get {
                return ResourceManager.GetString("IsOnReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зарегистрирован.
        /// </summary>
        internal static string IsRegistered {
            get {
                return ResourceManager.GetString("IsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - зарегистрированный ник.
        /// </summary>
        internal static string IsRegisteredNick {
            get {
                return ResourceManager.GetString("IsRegisteredNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * {0} зашёл(ла) на канал.
        /// </summary>
        internal static string JoinMessage {
            get {
                return ResourceManager.GetString("JoinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выкинул(а) с канала пользователя.
        /// </summary>
        internal static string KicksUserFormChannel {
            get {
                return ResourceManager.GetString("KicksUserFormChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канал {0} открыт!.
        /// </summary>
        internal static string KnockOpenMessage {
            get {
                return ResourceManager.GetString("KnockOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        internal static string LanguageEn {
            get {
                return ResourceManager.GetString("LanguageEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string LanguageRu {
            get {
                return ResourceManager.GetString("LanguageRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чат.
        /// </summary>
        internal static string LCChat {
            get {
                return ResourceManager.GetString("LCChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее.
        /// </summary>
        internal static string LCCommon {
            get {
                return ResourceManager.GetString("LCCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка ввода.
        /// </summary>
        internal static string LCInput {
            get {
                return ResourceManager.GetString("LCInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальное.
        /// </summary>
        internal static string LCSpecial {
            get {
                return ResourceManager.GetString("LCSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема канала.
        /// </summary>
        internal static string LCTopic {
            get {
                return ResourceManager.GetString("LCTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список пользователей.
        /// </summary>
        internal static string LCUsersList {
            get {
                return ResourceManager.GetString("LCUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель окон.
        /// </summary>
        internal static string LCWindowsPanel {
            get {
                return ResourceManager.GetString("LCWindowsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to покинул(а) канал.
        /// </summary>
        internal static string LeavesChannel {
            get {
                return ResourceManager.GetString("LeavesChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цирцея.
        /// </summary>
        internal static string LocalProgramName {
            get {
                return ResourceManager.GetString("LocalProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Лог завершён {0}.
        /// </summary>
        internal static string LogFinished {
            get {
                return ResourceManager.GetString("LogFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип логов.
        /// </summary>
        internal static string LogMode {
            get {
                return ResourceManager.GetString("LogMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влияет только на новые каналы.
        /// </summary>
        internal static string LogModeDescription {
            get {
                return ResourceManager.GetString("LogModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат форумов (без фона).
        /// </summary>
        internal static string LogModeForum {
            get {
                return ResourceManager.GetString("LogModeForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат форумов (с фоном в html).
        /// </summary>
        internal static string LogModeForum2 {
            get {
                return ResourceManager.GetString("LogModeForum2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html для форумов.
        /// </summary>
        internal static string LogModeHtmlForum {
            get {
                return ResourceManager.GetString("LogModeHtmlForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вести логи.
        /// </summary>
        internal static string LogModeNone {
            get {
                return ResourceManager.GetString("LogModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только текст.
        /// </summary>
        internal static string LogModeTxt {
            get {
                return ResourceManager.GetString("LogModeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Лог начат {0}.
        /// </summary>
        internal static string LogStarted {
            get {
                return ResourceManager.GetString("LogStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы отмечены как отсутствующий!.
        /// </summary>
        internal static string MarkedAsBeingAway {
            get {
                return ResourceManager.GetString("MarkedAsBeingAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы отмечены как присутствующий!.
        /// </summary>
        internal static string MarkedAsNotBeingAway {
            get {
                return ResourceManager.GetString("MarkedAsNotBeingAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маска.
        /// </summary>
        internal static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maximize {
            get {
                object obj = ResourceManager.GetObject("maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мультимедиа успешно установлено!.
        /// </summary>
        internal static string MediaInstalledSuccessfully {
            get {
                return ResourceManager.GetString("MediaInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мигать при получении сообщения в привате и упоминании ника на канале.
        /// </summary>
        internal static string MediumFlashMode {
            get {
                return ResourceManager.GetString("MediumFlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виден в меню.
        /// </summary>
        internal static string MenuVisible {
            get {
                return ResourceManager.GetString("MenuVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только серверы могут изменить этот режим у канала {0}!.
        /// </summary>
        internal static string Message468 {
            get {
                return ResourceManager.GetString("Message468", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize {
            get {
                object obj = ResourceManager.GetObject("minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анонимный (маски пользователей скрыты).
        /// </summary>
        internal static string ModeA {
            get {
                return ResourceManager.GetString("ModeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить маску бана.
        /// </summary>
        internal static string ModeB {
            get {
                return ResourceManager.GetString("ModeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить маски для лиц, неподвластных лимиту.
        /// </summary>
        internal static string ModeBigI {
            get {
                return ResourceManager.GetString("ModeBigI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стирать цвета в сообщениях.
        /// </summary>
        internal static string ModeBigS {
            get {
                return ResourceManager.GetString("ModeBigS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрет цветных сообщений.
        /// </summary>
        internal static string ModeC {
            get {
                return ResourceManager.GetString("ModeC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить допустимые маски (антибаны).
        /// </summary>
        internal static string ModeE {
            get {
                return ResourceManager.GetString("ModeE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход только по приглашению.
        /// </summary>
        internal static string ModeI {
            get {
                return ResourceManager.GetString("ModeI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить пароль для входа.
        /// </summary>
        internal static string ModeK {
            get {
                return ResourceManager.GetString("ModeK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лимит пользователей.
        /// </summary>
        internal static string ModeL {
            get {
                return ResourceManager.GetString("ModeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модерируемый.
        /// </summary>
        internal static string ModeM {
            get {
                return ResourceManager.GetString("ModeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to установлен режим.
        /// </summary>
        internal static string ModeMessage {
            get {
                return ResourceManager.GetString("ModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрет сообщений от пользователей вне канала.
        /// </summary>
        internal static string ModeN {
            get {
                return ResourceManager.GetString("ModeN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приватный.
        /// </summary>
        internal static string ModeP {
            get {
                return ResourceManager.GetString("ModeP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секретный.
        /// </summary>
        internal static string ModeS {
            get {
                return ResourceManager.GetString("ModeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топик устанавливают только операторы.
        /// </summary>
        internal static string ModeT {
            get {
                return ResourceManager.GetString("ModeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передача сообщения дня....
        /// </summary>
        internal static string MOTD {
            get {
                return ResourceManager.GetString("MOTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание! Был выпущен новый дистрибутив Цирцеи. Желательно удалить все прежние установочные файлы и использовать новый. Нажмите &quot;Да&quot;, чтобы позволить Цирцее самой скачать для вас новый установочный файл (около 1,5 Мб) и переустановиться. Нажмите &quot;Нет&quot;, чтобы отложить обновление до следующего раза. Автоматическая переустановка позволит избавить вашу версию от ряда древних ошибок и обеспечит вам гарантию нормальной работы в системе Windows XP и выше..
        /// </summary>
        internal static string NeedMajorUpgrade {
            get {
                return ResourceManager.GetString("NeedMajorUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточное число параметров у команды {0}!.
        /// </summary>
        internal static string NeedMoreParamsMessage {
            get {
                return ResourceManager.GetString("NeedMoreParamsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый канал.
        /// </summary>
        internal static string NewChannel {
            get {
                return ResourceManager.GetString("NewChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый сервер.
        /// </summary>
        internal static string NewServer {
            get {
                return ResourceManager.GetString("NewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ник.
        /// </summary>
        internal static string Nick {
            get {
                return ResourceManager.GetString("Nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка списка ников.
        /// </summary>
        internal static string NickListConfig {
            get {
                return ResourceManager.GetString("NickListConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ник {0} уже занят!.
        /// </summary>
        internal static string NicknameInUseMessage {
            get {
                return ResourceManager.GetString("NicknameInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информации об администрации сервера {0} не имеется.
        /// </summary>
        internal static string NoAdminInfoMessage {
            get {
                return ResourceManager.GetString("NoAdminInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удаётся загрузить сообщение дня!.
        /// </summary>
        internal static string NoMOTDMessage {
            get {
                return ResourceManager.GetString("NoMOTDMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В параметрах отсутствует никнейм.
        /// </summary>
        internal static string NoNicknameGivenMessage {
            get {
                return ResourceManager.GetString("NoNicknameGivenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определён источник сообщений.
        /// </summary>
        internal static string NoOriginMessage {
            get {
                return ResourceManager.GetString("NoOriginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для класса {1} не задан параметр {0}.
        /// </summary>
        internal static string NoParamForInstaller {
            get {
                return ResourceManager.GetString("NoParamForInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет полномочий IRC оператора!.
        /// </summary>
        internal static string NoPrivileges {
            get {
                return ResourceManager.GetString("NoPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не существует канал: {0}.
        /// </summary>
        internal static string NoSuchChannelMessage {
            get {
                return ResourceManager.GetString("NoSuchChannelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден сервер {0}.
        /// </summary>
        internal static string NoSuchServerMessage {
            get {
                return ResourceManager.GetString("NoSuchServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в сети.
        /// </summary>
        internal static string NotAway {
            get {
                return ResourceManager.GetString("NotAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно параметров.
        /// </summary>
        internal static string NotEnoughParametresSpecified {
            get {
                return ResourceManager.GetString("NotEnoughParametresSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет текста для отправки!.
        /// </summary>
        internal static string NoTextToSendMessage {
            get {
                return ResourceManager.GetString("NoTextToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не входит в ваш список допустимых лиц.
        /// </summary>
        internal static string NotInAcceptList {
            get {
                return ResourceManager.GetString("NotInAcceptList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не находитесь на канале {0}!.
        /// </summary>
        internal static string NotOnChannelMessage {
            get {
                return ResourceManager.GetString("NotOnChannelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не указан домен верхнего уровня.
        /// </summary>
        internal static string NoTopLevelDomainMessage {
            get {
                return ResourceManager.GetString("NoTopLevelDomainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : сперва нужно зарегистрироваться!.
        /// </summary>
        internal static string NotRegisteredMessage {
            get {
                return ResourceManager.GetString("NotRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используется по умолчанию.
        /// </summary>
        internal static string NotUsed {
            get {
                return ResourceManager.GetString("NotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теперь ваш ник.
        /// </summary>
        internal static string NowYourNickIs {
            get {
                return ResourceManager.GetString("NowYourNickIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать команду открытия привата на сервере.
        /// </summary>
        internal static string OpenPrivateVisible {
            get {
                return ResourceManager.GetString("OpenPrivateVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операторов онлайн.
        /// </summary>
        internal static string OpsOnline {
            get {
                return ResourceManager.GetString("OpsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для входа на канал необходимо ввести ключ.
        /// </summary>
        internal static string PasswordNeeded {
            get {
                return ResourceManager.GetString("PasswordNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: пинг - {1}.
        /// </summary>
        internal static string PingAnswer {
            get {
                return ResourceManager.GetString("PingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисконнект через.
        /// </summary>
        internal static string PingServer {
            get {
                return ResourceManager.GetString("PingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщать о дисконнекте при неответе сервера в течение (с).
        /// </summary>
        internal static string PingServerDescription {
            get {
                return ResourceManager.GetString("PingServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всегда.
        /// </summary>
        internal static string PlayModeAll {
            get {
                return ResourceManager.GetString("PlayModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никогда.
        /// </summary>
        internal static string PlayModeNone {
            get {
                return ResourceManager.GetString("PlayModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только по команде оператора.
        /// </summary>
        internal static string PlayModeOpOnly {
            get {
                return ResourceManager.GetString("PlayModeOpOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играть мультимедиа по команде play.
        /// </summary>
        internal static string PlayMusic {
            get {
                return ResourceManager.GetString("PlayMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играть медиафайлы и показывать изображения при получении на канале команды play белым цветом.
        /// </summary>
        internal static string PlayMusicDescription {
            get {
                return ResourceManager.GetString("PlayMusicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код цвета сообщений (от 0 до 98).
        /// </summary>
        internal static string PrintForeColor {
            get {
                return ResourceManager.GetString("PrintForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры прокси-сервера.
        /// </summary>
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда авторизации.
        /// </summary>
        internal static string PutRegisterMessage {
            get {
                return ResourceManager.GetString("PutRegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматически создавать команду для ввода пароля зарегистрированного ника.
        /// </summary>
        internal static string PutRegisterMessageDescription {
            get {
                return ResourceManager.GetString("PutRegisterMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение при выходе из программы.
        /// </summary>
        internal static string QuitMessage {
            get {
                return ResourceManager.GetString("QuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вышел(ла) из IRC.
        /// </summary>
        internal static string QuitsIRC {
            get {
                return ResourceManager.GetString("QuitsIRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настоящее имя.
        /// </summary>
        internal static string RealName {
            get {
                return ResourceManager.GetString("RealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно пригласили {0} на {1}.
        /// </summary>
        internal static string RplInvitingMessage {
            get {
                return ResourceManager.GetString("RplInvitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string RplSingleUserInfoMessage {
            get {
                return ResourceManager.GetString("RplSingleUserInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о пользователях:.
        /// </summary>
        internal static string RplUserInfoMessage {
            get {
                return ResourceManager.GetString("RplUserInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить установщик.
        /// </summary>
        internal static string SaveInstallerAs {
            get {
                return ResourceManager.GetString("SaveInstallerAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранять пароли зарегистрированных ников.
        /// </summary>
        internal static string SavePasswords {
            get {
                return ResourceManager.GetString("SavePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selectUser {
            get {
                object obj = ResourceManager.GetObject("selectUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} отправляет вам сообщение, но вы находитесь в режиме +g и не можете его получить.
        /// </summary>
        internal static string SendingToG {
            get {
                return ResourceManager.GetString("SendingToG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тестовый режим.
        /// </summary>
        internal static string ServerDebugMode {
            get {
                return ResourceManager.GetString("ServerDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрыв соединения с сервером.
        /// </summary>
        internal static string ServerLinkClosed {
            get {
                return ResourceManager.GetString("ServerLinkClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер перегружен и не может выполнить вашу команду. Пожалуйста, попробуйте чуть позже.
        /// </summary>
        internal static string ServerOverload {
            get {
                return ResourceManager.GetString("ServerOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время на сервере {0}: {1}.
        /// </summary>
        internal static string ServerTime {
            get {
                return ResourceManager.GetString("ServerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В настоящий момент сервисы отключены!.
        /// </summary>
        internal static string ServiceDownMessage {
            get {
                return ResourceManager.GetString("ServiceDownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to установлена.
        /// </summary>
        internal static string SetBy {
            get {
                return ResourceManager.GetString("SetBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить новую тему канала?.
        /// </summary>
        internal static string SetNewTopic {
            get {
                return ResourceManager.GetString("SetNewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль для входа на канал.
        /// </summary>
        internal static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to установил(а) режим.
        /// </summary>
        internal static string SetsMode {
            get {
                return ResourceManager.GetString("SetsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to установил(а) новый топик канала.
        /// </summary>
        internal static string SetsNewTopic {
            get {
                return ResourceManager.GetString("SetsNewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки доступны по правой кнопке мыши.
        /// </summary>
        internal static string SettingsAvailability {
            get {
                return ResourceManager.GetString("SettingsAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распаковывающийся архив с дополнением.
        /// </summary>
        internal static string SFXAddon {
            get {
                return ResourceManager.GetString("SFXAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать панель редактирования.
        /// </summary>
        internal static string ShowEditorPanel {
            get {
                return ResourceManager.GetString("ShowEditorPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отделять непрочитанный текст разделителем.
        /// </summary>
        internal static string ShowReadSplitters {
            get {
                return ResourceManager.GetString("ShowReadSplitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В неактивное окно чата будет добавляться дополнительная строка, отделяющая непрочитанные сообщения.
        /// </summary>
        internal static string ShowReadSplittersDescription {
            get {
                return ResourceManager.GetString("ShowReadSplittersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачивать мультимедиа из сети по команде url.
        /// </summary>
        internal static string ShowUrlOnCmd {
            get {
                return ResourceManager.GetString("ShowUrlOnCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматически скачивать изображения, видео и аудио и показывать/проигрывать их при получении на канале команды url белым цветом.
        /// </summary>
        internal static string ShowUrlOnCmdDescription {
            get {
                return ResourceManager.GetString("ShowUrlOnCmdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задано ни одного ника. Задайте хотя бы один!.
        /// </summary>
        internal static string SpecifyOneNickAtLeast {
            get {
                return ResourceManager.GetString("SpecifyOneNickAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим запуска.
        /// </summary>
        internal static string StartMode {
            get {
                return ResourceManager.GetString("StartMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время у {0}: {1}.
        /// </summary>
        internal static string TimeAnswer {
            get {
                return ResourceManager.GetString("TimeAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TooFastTargetChangeMessage {
            get {
                return ResourceManager.GetString("TooFastTargetChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы зашли на предельно допустимое число каналов!.
        /// </summary>
        internal static string TooManyChannelsMessage {
            get {
                return ResourceManager.GetString("TooManyChannelsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to слишком много получателей, сообщение не отправлено.
        /// </summary>
        internal static string TooManyTargetsMessage {
            get {
                return ResourceManager.GetString("TooManyTargetsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топик создан.
        /// </summary>
        internal static string TopicCreated {
            get {
                return ResourceManager.GetString("TopicCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топик установил(а).
        /// </summary>
        internal static string TopicSetBy {
            get {
                return ResourceManager.GetString("TopicSetBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего каналов.
        /// </summary>
        internal static string TotalChannels {
            get {
                return ResourceManager.GetString("TotalChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего пользователей.
        /// </summary>
        internal static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша кодировка теперь {0}.
        /// </summary>
        internal static string TranslationSchemeMessage {
            get {
                return ResourceManager.GetString("TranslationSchemeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная команда: {0}.
        /// </summary>
        internal static string UnknownCommandMessage {
            get {
                return ResourceManager.GetString("UnknownCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный режим канала &quot;{0}&quot;!.
        /// </summary>
        internal static string UnknownModeMessage {
            get {
                return ResourceManager.GetString("UnknownModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недостаточное число параметров.
        /// </summary>
        internal static string UnsufficientParams {
            get {
                return ResourceManager.GetString("UnsufficientParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При поиске обновлений возникла ошибка: {0}.
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При поиске обновления возникла следующая ошибка: {0}.
        /// </summary>
        internal static string UpdateException {
            get {
                return ResourceManager.GetString("UpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_comment {
            get {
                object obj = ResourceManager.GetObject("user_comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap userData {
            get {
                object obj = ResourceManager.GetObject("userData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя узнать или изменить режимы другого пользователя!.
        /// </summary>
        internal static string UserDontMatchMessage {
            get {
                return ResourceManager.GetString("UserDontMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не активен уже {1} секунд.
        /// </summary>
        internal static string UserIdle {
            get {
                return ResourceManager.GetString("UserIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о пользователе {0}: {1}.
        /// </summary>
        internal static string UserInfoAnswer {
            get {
                return ResourceManager.GetString("UserInfoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь {0} находится уже на канале {1}!.
        /// </summary>
        internal static string UserOnChannelMessage {
            get {
                return ResourceManager.GetString("UserOnChannelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда USERS отключена на данном сервере.
        /// </summary>
        internal static string UsersDisabledMessage {
            get {
                return ResourceManager.GetString("UsersDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На канале {0} находятся: {1}.
        /// </summary>
        internal static string UsersOnChannel {
            get {
                return ResourceManager.GetString("UsersOnChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} использует клиент {1}.
        /// </summary>
        internal static string VersionAnswer {
            get {
                return ResourceManager.GetString("VersionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия ПО сервера {0}: {1} ({2}).
        /// </summary>
        internal static string VersionMessage {
            get {
                return ResourceManager.GetString("VersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение данных....
        /// </summary>
        internal static string WaitingForUserInfo {
            get {
                return ResourceManager.GetString("WaitingForUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пинговать сервер при его молчании более (с).
        /// </summary>
        internal static string WaitServer {
            get {
                return ResourceManager.GetString("WaitServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 отключает пингование.
        /// </summary>
        internal static string WaitServerDescription {
            get {
                return ResourceManager.GetString("WaitServerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исторической информации о нике {0} не имеется.
        /// </summary>
        internal static string WasNoSuchNick {
            get {
                return ResourceManager.GetString("WasNoSuchNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не мигать.
        /// </summary>
        internal static string WeakFlashMode {
            get {
                return ResourceManager.GetString("WeakFlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о {7} ({0}@{1}): канал: {2}, сервер: {3}, прыжков: {4}, информация: {5}, реальное имя: {6}.
        /// </summary>
        internal static string WhoReply {
            get {
                return ResourceManager.GetString("WhoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} был {1}@{2} (реальное имя: {3}).
        /// </summary>
        internal static string WhoWasUser {
            get {
                return ResourceManager.GetString("WhoWasUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to недопустимый символ в домене верхнего уровня.
        /// </summary>
        internal static string WildTopLevelMessage {
            get {
                return ResourceManager.GetString("WildTopLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оператор канала.
        /// </summary>
        internal static string WithOp {
            get {
                return ResourceManager.GetString("WithOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to голос на канале.
        /// </summary>
        internal static string WithVoice {
            get {
                return ResourceManager.GetString("WithVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to со словами: {0}.
        /// </summary>
        internal static string WithWords {
            get {
                return ResourceManager.GetString("WithWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задано неверное имя файла.
        /// </summary>
        internal static string WrongFileName {
            get {
                return ResourceManager.GetString("WrongFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теперь вы IRC оператор.
        /// </summary>
        internal static string YouAreAnIRCOp {
            get {
                return ResourceManager.GetString("YouAreAnIRCOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не на канале.
        /// </summary>
        internal static string YouAreNotOnAChannel {
            get {
                return ResourceManager.GetString("YouAreNotOnAChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш режим.
        /// </summary>
        internal static string YourModeIs {
            get {
                return ResourceManager.GetString("YourModeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы были выкинуты с канала {0} пользователем {1}.
        /// </summary>
        internal static string YouWasKicked {
            get {
                return ResourceManager.GetString("YouWasKicked", resourceCulture);
            }
        }
    }
}
