//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCWindow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class UISettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UISettings defaultInstance = ((UISettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UISettings())));
        
        public static UISettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 12.75pt")]
        public global::System.Drawing.Font TopicFont {
            get {
                return ((global::System.Drawing.Font)(this["TopicFont"]));
            }
            set {
                this["TopicFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[HH:mm:ss]")]
        public string DateTimeFormat {
            get {
                return ((string)(this["DateTimeFormat"]));
            }
            set {
                this["DateTimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CIRCe by Vladimir Khil")]
        public string QuitMessage {
            get {
                return ((string)(this["QuitMessage"]));
            }
            set {
                this["QuitMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 11.25pt")]
        public global::System.Drawing.Font ChatFont {
            get {
                return ((global::System.Drawing.Font)(this["ChatFont"]));
            }
            set {
                this["ChatFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GhostWhite")]
        public global::System.Drawing.Color ChatBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ChatBackColor"]));
            }
            set {
                this["ChatBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 12.75pt")]
        public global::System.Drawing.Font PrintFont {
            get {
                return ((global::System.Drawing.Font)(this["PrintFont"]));
            }
            set {
                this["PrintFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GhostWhite")]
        public global::System.Drawing.Color PrintBackColor {
            get {
                return ((global::System.Drawing.Color)(this["PrintBackColor"]));
            }
            set {
                this["PrintBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lavender")]
        public global::System.Drawing.Color TopicBackColor {
            get {
                return ((global::System.Drawing.Color)(this["TopicBackColor"]));
            }
            set {
                this["TopicBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 11.25pt")]
        public global::System.Drawing.Font UsersFont {
            get {
                return ((global::System.Drawing.Font)(this["UsersFont"]));
            }
            set {
                this["UsersFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GhostWhite")]
        public global::System.Drawing.Color UsersBackColor {
            get {
                return ((global::System.Drawing.Color)(this["UsersBackColor"]));
            }
            set {
                this["UsersBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 9.75pt, style=Bold, Italic")]
        public global::System.Drawing.Font TreeFont {
            get {
                return ((global::System.Drawing.Font)(this["TreeFont"]));
            }
            set {
                this["TreeFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Azure")]
        public global::System.Drawing.Color TreeBackColor {
            get {
                return ((global::System.Drawing.Color)(this["TreeBackColor"]));
            }
            set {
                this["TreeBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MessagesColor {
            get {
                return ((int)(this["MessagesColor"]));
            }
            set {
                this["MessagesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ServerConnectedColor {
            get {
                return ((global::System.Drawing.Color)(this["ServerConnectedColor"]));
            }
            set {
                this["ServerConnectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color ServerDisconnectedColor {
            get {
                return ((global::System.Drawing.Color)(this["ServerDisconnectedColor"]));
            }
            set {
                this["ServerDisconnectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thistle")]
        public global::System.Drawing.Color SelfOnChannelBackColor {
            get {
                return ((global::System.Drawing.Color)(this["SelfOnChannelBackColor"]));
            }
            set {
                this["SelfOnChannelBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color SelfOnChannelForeColor {
            get {
                return ((global::System.Drawing.Color)(this["SelfOnChannelForeColor"]));
            }
            set {
                this["SelfOnChannelForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("819, 509")]
        public global::System.Drawing.Size IRCWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["IRCWindowSize"]));
            }
            set {
                this["IRCWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Txt")]
        public global::IRCProviders.LogMode LogMode {
            get {
                return ((global::IRCProviders.LogMode)(this["LogMode"]));
            }
            set {
                this["LogMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayMusic {
            get {
                return ((bool)(this["PlayMusic"]));
            }
            set {
                this["PlayMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PutRegisterMessage {
            get {
                return ((bool)(this["PutRegisterMessage"]));
            }
            set {
                this["PutRegisterMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowUrlOnCmd {
            get {
                return ((bool)(this["ShowUrlOnCmd"]));
            }
            set {
                this["ShowUrlOnCmd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowReadSplitters {
            get {
                return ((bool)(this["ShowReadSplitters"]));
            }
            set {
                this["ShowReadSplitters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenPrivateVisible {
            get {
                return ((bool)(this["OpenPrivateVisible"]));
            }
            set {
                this["OpenPrivateVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public global::IRCProviders.PlayMode PlayMusicExt {
            get {
                return ((global::IRCProviders.PlayMode)(this["PlayMusicExt"]));
            }
            set {
                this["PlayMusicExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public global::IRCProviders.PlayMode UrlExt {
            get {
                return ((global::IRCProviders.PlayMode)(this["UrlExt"]));
            }
            set {
                this["UrlExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Default)")]
        public global::System.Globalization.CultureInfo Language {
            get {
                return ((global::System.Globalization.CultureInfo)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public uint PingServer {
            get {
                return ((uint)(this["PingServer"]));
            }
            set {
                this["PingServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public uint WaitServer {
            get {
                return ((uint)(this["WaitServer"]));
            }
            set {
                this["WaitServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SavePasswords {
            get {
                return ((bool)(this["SavePasswords"]));
            }
            set {
                this["SavePasswords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<FlashParams xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <FlashingMode>Meduim</FlashingMode>
  <FlashOnNick>true</FlashOnNick>
  <FlashOnPrivate>true</FlashOnPrivate>
  <UseBlackList>false</UseBlackList>
  <UseWhiteList>false</UseWhiteList>
  <BlackList />
  <WhiteList />
</FlashParams>")]
        public global::IRCProviders.FlashParams FlashingParams {
            get {
                return ((global::IRCProviders.FlashParams)(this["FlashingParams"]));
            }
            set {
                this["FlashingParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyOnCtcp {
            get {
                return ((bool)(this["NotifyOnCtcp"]));
            }
            set {
                this["NotifyOnCtcp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyOnNoMedia {
            get {
                return ((bool)(this["NotifyOnNoMedia"]));
            }
            set {
                this["NotifyOnNoMedia"] = value;
            }
        }
    }
}
